version: '3'

services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - my_network

  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=testdb
    networks:
      - my_network


networks:
  my_network:

volumes:
  mongodb_data:
